### ISSUE TITLE
Redesign of itunes connect

### ISSUE THREAD

**Issue by spidfire** [kovpas/itc.cli#38]
I saw Itunes connect is now switched to an angular frontend
Maybe we can make a joint effort to document the api calls (and afterward create the app)? 

I've found some (easy) api calls already

summary of your apps:
https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/manageyourapps/summary

Details of one app:
https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/detail/{appid}

Versions:
https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/version/{appid}

**Comment by KrauseFx** [comment]
I want to thank you all for posting the URLs here, I started integrating them into [deliver](https://github.com/KrauseFx/deliver): https://github.com/KrauseFx/deliver/pull/113/files

**Comment by kovpas** [comment]
@KrauseFx :+1:

**Comment by KrauseFx** [comment]
Not 100% done yet, but I started an open source documentation of the iTunes Connect API: https://github.com/fastlane/itc-api-docs/

If you know anything else, feel free to contribute to the project :+1:

**Comment by KrauseFx** [comment]
You might be interested in what I'm working on right now: https://github.com/fastlane/spaceship/pull/58

I released [spaceship](https://spaceship.airforce), which will soon be able to also access all relevant features of iTunes Connect using a Ruby library. Let me know what you think.

**Comment by jimthedev** [comment]
Nice @krausefx! How is this different from https://github.com/nomad/shenzhen?

**Comment by jimthedev** [comment]
Also @krausefx, are you aware of any thing that does this for android apks?

**Comment by KrauseFx** [comment]
@jimthedev `shenzhen` is almost in no way related to `spaceship`. `spaceship` exposes a Ruby API for all resources of the Dev Portal and iTunes Connect. So you can write your own tools with it, without having to think about the underlying API from Apple. `shenzhen` is only about building and uploading your `ipa` file. It is actually integrated into [fastlane](https://github.com/KrauseFx/fastlane).

I'm actually working on something similar for Android, you can follow the [fastlane](https://github.com/KrauseFx/fastlane) project to stay up to date :+1:
